---
title: "stl lead inequity"
author: "Marie Rivers"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(skimr)
library(here)
```

```{r}
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";")

stl_lead <- stl_lead %>% clean_names
```
## create a new data frame called stl_lead_prop that has one additional column called prop_white that returns the percent of each census tract identifying as white (white/total pop * 100)
```{r}
stl_lead_prop <- stl_lead %>%
  mutate(prop_white = white / total_pop * 100) %>%
  mutate(pct_elevated = str_replace(pct_elevated,
                                    pattern = ",",
                                    replacement = ".")) %>%
  mutate(pct_elevated = as.numeric(pct_elevated))
stl_lead_prop 
```

```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = pct_elevated, y = prop_white)) +
  geom_point() +
  labs(subtitle = "In census tracks with a high percent white population, lead concentrations tend to be lower. In census tracks with lower percent white population, lead concentrations tend to be higher.")

### In census tracks with a high percent white population, lead concentrations tend to be lower. In census tracks with lower percent white population, lead concentrations tend to be higher.
stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)
```
## Histogram
```{r}
stl_lead_histogram <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(aes(color = "cyan"))

stl_lead_histogram

ggsave(here::here("figs", "stl_lead_histogram.png"))
```



